data:
  params:
    batch_size: 1
    num_workers: 1
    test:
      params:
        apply_positional_encoding: false
        apply_transform: true
        size: 256
      target: utils.dataloader.LayeredDepthImageTest
    wrap: true
  target: main.DataModuleFromConfig
lightning:
  callbacks:
    image_logger:
      params:
        batch_frequency: 1000
        clamp: false
        increase_log_steps: false
        max_images: 8
      target: main.ImageLogger
  trainer:
    accumulate_grad_batches: 2
    benchmark: true
model:
  base_learning_rate: 4.5e-06
  params:
    ckpt_path: logs/2024-02-21T20-08-43_autoencoder-kl-f4/checkpoints/epoch=000265.ckpt
    ddconfig:
      attn_resolutions: []
      ch: 64
      ch_mult:
      - 1
      - 2
      - 4
      double_z: true
      dropout: 0.0
      in_channels: 3
      num_res_blocks: 2
      out_ch: 3
      resolution: 256
      z_channels: 4
    embed_dim: 4
    image_key: ldi
    loss_path: loss_logs/{now}_exp18_v3_test/
    lossconfig:
      params:
        diff_loss_weight: 2
        disc_start: 50000001
        disc_weight: 0.0
        kl_weight: 0.005
        perceptual_weight: 0.0
      target: modules.losses.contperceptual.LPIPSWithDiscriminator
    monitor: val/rec_loss
  target: models.autoencoder.AutoencoderKL
