data:
  params:
    batch_size: 2
    num_workers: 4
    train:
      params:
        apply_positional_encoding: false
        apply_transform: true
        flip: 0.5
        multiply_data: 1
        size: 256
      target: utils.dataloader.LayeredDepthImageTrain
    validation:
      params:
        apply_positional_encoding: false
        apply_transform: true
        size: 256
      target: utils.dataloader.LayeredDepthImageValidation
    wrap: true
  target: main.DataModuleFromConfig
lightning:
  callbacks:
    image_logger:
      params:
        batch_frequency: 1000
        clamp: false
        increase_log_steps: false
        max_images: 8
      target: main.ImageLogger
  trainer:
    accumulate_grad_batches: 2
    benchmark: true
model:
  base_learning_rate: 4.5e-06
  params:
    ddconfig:
      attn_resolutions: []
      ch: 64
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      double_z: true
      dropout: 0.0
      in_channels: 3
      num_res_blocks: 2
      out_ch: 3
      resolution: 256
      z_channels: 4
    embed_dim: 4
    image_key: ldi
    loss_path: loss_logs/exp1_autoencoder_kl_f4/
    lossconfig:
      params:
        disc_start: 50001
        disc_weight: 0.5
        kl_weight: 1.0e-06
      target: modules.losses.contperceptual.LPIPSWithDiscriminator
    monitor: val/rec_loss
  target: models.autoencoder.AutoencoderKL
